title: "TechWizCo"
email: andre@techwizco.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.avif'
favicon: 'assets/images/favicon.ico'
author: john
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
#ganalytics: "G-SMGQ71PCWS"

# gzip compress the following extensions
gzip:
  replace_files: true
  extensions:
    - '.html'
    - '.css'
    - '.js'
    - '.svg'

# Authors
authors:
  andre:
    name: Andre
    display_name: Andre
    avatar: 'assets/images/sal.avif'
    email: andre@techwizco.com
    web: https://techwizco.com/
    twitter: https://twitter.com/
    description: "Andre is a widely respected voice in artificial intelligence, cloud development, and embedded systems technologies."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.avif'
    email: info@techwizco.com
    web: https://techwizco.com
    twitter: https://twitter.com/
    description: "John is a renowned technology expert and author with a passion for exploring the latest advancements in the field. With a wealth of experience and a deep understanding of the industry, John provides valuable insights and analysis on the trends shaping the future of technology."
  sam:
    name: Sam
    display_name: Samantha
    avatar: 'assets/images/sam.avif'
    email: info@techwizco.com
    web: https://techwizco.com
    twitter: https://twitter.com/
    description: "Samantha is a leading technology writer and authority, known for her in-depth coverage and analysis of the latest trends and innovations in the industry. Her extensive knowledge and experience make her a valuable resource for understanding the impact of technology on our world."

# Social
social:
  instagram: https://www.instagram.com/
  facebook: https://www.facebook.com/
  twitter: https://twitter.com/

# Default exceptions from sitemap for jekyll-sitemap plugin
defaults:
  -
    scope:
      path:       "pages/*"
    values:
      sitemap: false
      
# Plugins
url: "https://techwizco.com"
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-archives
- jekyll-gzip
- jekyll-seo-tag